import os
import torch
import numpy as np
import rasterio
from rasterio.windows import Window
from rasterio import features  # Used for vector to raster conversion
from torch.utils.data import Dataset
from datetime import datetime, timedelta
import json
from tqdm import tqdm
import pandas as pd
import geopandas as gpd  # Used for reading SHP

# --- Path Configuration ---
DATA_PATHS = {
    'Albedo': r'E:\graduation project\data_degree0.1\Albedo',
    'LST': r'E:\graduation project\data_degree0.1\LST',
    'NDVI': r'E:\graduation project\data_degree0.1\NDVI',
    'SM': r'E:\graduation project\data_degree0.1\SM',
    'Wind': r'E:\graduation project\data_degree0.1\windspeed',

    # [Removed] T2m Input
    # 'T2m': r'E:\graduation project\data_degree0.1\T2m',

    # [Target] High-resolution ground truth generated by RF (retained as label)
    'Label': r'E:\graduation project\data_degree0.1\T2m',

    # [Static] Topographic data
    'Aspect': r'E:\graduation project\data_degree0.1\aspect\aspect_area_463.tif',
    'DEM': r'E:\graduation project\data_degree0.1\DEM\DEM_area_463.tif',
    'Slope': r'E:\graduation project\data_degree0.1\slope\slope_area.tif',

    # [Station] Station data folder
    'Stations': r'E:\Ta_fusion\paper_11\data\yangtze_river_delta_station_data_2016\yangtze_stations_NOAA_daily',

    # [Boundary] Boundary SHP file path
    'Boundary': r'E:\graduation project\coding\详细边界\boundary.shp'
}

STATS_FILE = 'dataset_stats.json'

# Default ranges (T2m removed)
DEFAULT_RANGES = {
    'Albedo': (0.0, 1.0), 'LST': (-30, 50), 'NDVI': (-0.2, 1.0),
    'SM': (0.0, 1.0), 'Wind': (0.0, 20.0),
    'Label': (-50, 50),
    'Aspect': (0.0, 360.0), 'DEM': (-36, 2020.0), 'Slope': (0.0, 90.0)
}


def load_data_stats():
    if os.path.exists(STATS_FILE):
        with open(STATS_FILE, 'r') as f:
            return json.load(f)
    return DEFAULT_RANGES


# Global variables
PHYSICAL_RANGES = load_data_stats()


def calculate_and_save_stats():
    """Scan dataset to calculate normalization statistics"""
    print("Scanning dataset to calculate normalization statistics...")
    stats = {}

    # 1. Static variables
    static_vars = ['Aspect', 'DEM', 'Slope']
    for var in static_vars:
        path = DATA_PATHS[var]
        if not os.path.exists(path): continue
        with rasterio.open(path) as src:
            data = src.read(1)
            valid_mask = (data > -1e30)
            if src.nodata is not None:
                valid_mask &= (data != src.nodata)
            if valid_mask.sum() > 0:
                vmin = float(data[valid_mask].min())
                vmax = float(data[valid_mask].max())
                stats[var] = [vmin, vmax]
                print(f"  [{var}] Range: {vmin:.2f} ~ {vmax:.2f}")

    # 2. Dynamic variables (T2m removed)
    dynamic_vars = ['Albedo', 'LST', 'NDVI', 'SM', 'Wind', 'Label']
    for var in dynamic_vars:
        folder = DATA_PATHS[var]
        if not os.path.exists(folder): continue
        files = [os.path.join(folder, f) for f in os.listdir(folder) if f.endswith('.tif')]
        if not files: continue

        global_min = float('inf')
        global_max = float('-inf')

        print(f"  Scanning {var} ({len(files)} files)...")
        for fpath in tqdm(files):
            try:
                with rasterio.open(fpath) as src:
                    data = src.read(1)
                    valid_mask = (data > -1e30)
                    if src.nodata is not None:
                        valid_mask &= (data != src.nodata)
                    if valid_mask.sum() > 0:
                        batch_min = data[valid_mask].min()
                        batch_max = data[valid_mask].max()
                        if batch_min < global_min: global_min = float(batch_min)
                        if batch_max > global_max: global_max = float(batch_max)
            except:
                pass
        stats[var] = [global_min, global_max]
        print(f"  => [{var}] Final Range: {global_min:.2f} ~ {global_max:.2f}")

    with open(STATS_FILE, 'w') as f:
        json.dump(stats, f, indent=4)
    print(f"✅ Statistics saved to {STATS_FILE}")

    global PHYSICAL_RANGES
    PHYSICAL_RANGES = stats


class CausalDownscalingDataset(Dataset):
    def __init__(self, start_date='2016-01-01', end_date='2016-12-31',
                 patch_size=512, is_train=True):
        self.dates = self._generate_date_list(start_date, end_date)
        self.patch_size = patch_size
        self.is_train = is_train
        self.ranges = PHYSICAL_RANGES

        # 1. Preload static data & get geographical transform parameters
        self.static_data = {}
        self.transform = None
        self.inv_transform = None
        self.crs = None

        print("Preloading static data...")
        if os.path.exists(DATA_PATHS['DEM']):
            with rasterio.open(DATA_PATHS['DEM']) as src:
                self.transform = src.transform
                self.inv_transform = ~src.transform
                self.h, self.w = src.shape
                self.crs = src.crs

                data = src.read(1)
                tensor = torch.from_numpy(data).float().unsqueeze(0)
                min_v, max_v = self.ranges.get('DEM', (-36, 2020))
                tensor = (tensor - min_v) / (max_v - min_v + 1e-6)
                self.static_data['DEM'] = torch.nan_to_num(tensor, nan=0.0)
        else:
            raise FileNotFoundError("DEM file must be provided to determine coordinate system!")

        # Process boundary mask
        self.boundary_mask = self._load_boundary_mask()

        # Load other static data
        for name in ['Aspect', 'Slope']:
            if os.path.exists(DATA_PATHS[name]):
                self.static_data[name] = self._read_and_normalize(DATA_PATHS[name], name)
            else:
                self.static_data[name] = torch.zeros(1, self.h, self.w)

        self.file_cache = self._cache_dynamic_files()
        self.station_data_cache = self._preload_station_data()

    def _load_boundary_mask(self):
        """Read SHP and convert to raster mask"""
        shp_path = DATA_PATHS.get('Boundary')
        if not shp_path or not os.path.exists(shp_path):
            print("⚠️ Warning: SHP boundary file not found, will process full image.")
            return torch.ones(1, self.h, self.w)

        print(f"Processing boundary mask: {shp_path}")
        try:
            gdf = gpd.read_file(shp_path)
            if gdf.crs != self.crs:
                print(f"  Converting SHP CRS: {gdf.crs} -> {self.crs}")
                gdf = gdf.to_crs(self.crs)

            shapes = [(geom, 1) for geom in gdf.geometry]
            mask_np = features.rasterize(
                shapes=shapes,
                out_shape=(self.h, self.w),
                transform=self.transform,
                fill=0,
                dtype='uint8'
            )
            valid_ratio = mask_np.mean()
            print(f"✅ Boundary mask generated. Valid area ratio: {valid_ratio * 100:.2f}%")
            return torch.from_numpy(mask_np).float().unsqueeze(0)
        except Exception as e:
            print(f"❌ SHP processing failed: {e}, defaulting to full image.")
            return torch.ones(1, self.h, self.w)

    def _generate_date_list(self, start, end):
        s = datetime.strptime(start, "%Y-%m-%d")
        e = datetime.strptime(end, "%Y-%m-%d")
        delta = e - s
        return [s + timedelta(days=i) for i in range(delta.days + 1)]

    def _cache_dynamic_files(self):
        cache = {}
        # T2m removed
        dyn_vars = ['Albedo', 'LST', 'NDVI', 'SM', 'Wind', 'Label']
        for var in dyn_vars:
            cache[var] = {}
            folder = DATA_PATHS[var]
            if not os.path.exists(folder): continue
            for f in os.listdir(folder):
                if f.endswith('.tif') or f.endswith('.tiff'):
                    cache[var][f] = os.path.join(folder, f)
        return cache

    def _preload_station_data(self):
        """Read all station CSVs"""
        station_dir = DATA_PATHS.get('Stations')
        if not station_dir or not os.path.exists(station_dir):
            return {}

        print("Preloading station observation data...")
        cache = {}
        csv_files = [f for f in os.listdir(station_dir) if f.endswith('.csv')]
        count_valid = 0

        for csv_file in tqdm(csv_files):
            path = os.path.join(station_dir, csv_file)
            try:
                df = pd.read_csv(path)
                df.columns = [c.strip() for c in df.columns]
                required_cols = ['DATE', 'LATITUDE', 'LONGITUDE', 'TEMP']
                if not all(col in df.columns for col in required_cols):
                    continue

                cols, rows = self.inv_transform * (df['LONGITUDE'].values, df['LATITUDE'].values)
                rows = np.round(rows).astype(int)
                cols = np.round(cols).astype(int)
                temp_c = (df['TEMP'].values - 32.0) * 5.0 / 9.0

                for i in range(len(df)):
                    date_str = str(df['DATE'][i]).strip()
                    try:
                        dt = pd.to_datetime(date_str)
                        key = dt.strftime("%Y%m%d")
                    except:
                        continue
                    r, c = rows[i], cols[i]
                    val = temp_c[i]
                    if 0 <= r < self.h and 0 <= c < self.w:
                        if key not in cache:
                            cache[key] = []
                        cache[key].append((r, c, val))
                        count_valid += 1
            except Exception as e:
                print(f"Error reading {csv_file}: {e}")
        return cache

    def _normalize(self, tensor, var_name):
        if var_name in self.ranges:
            min_val, max_val = self.ranges[var_name]
            tensor = torch.clamp(tensor, min_val, max_val)
            tensor = (tensor - min_val) / (max_val - min_val + 1e-6)
        return tensor

    def _read_and_normalize(self, path, var_name, window=None):
        try:
            with rasterio.open(path) as src:
                if window:
                    data = src.read(1, window=window)
                else:
                    data = src.read(1)

                nodata_val = src.nodata
                if nodata_val is not None:
                    data = np.where(data == nodata_val, np.nan, data)
                data = np.where(data < -1e30, np.nan, data)

                tensor = torch.from_numpy(data).float().unsqueeze(0)
                tensor = self._normalize(tensor, var_name)
                tensor = torch.nan_to_num(tensor, nan=0.0)
                return tensor
        except Exception:
            target_h = window.height if window else self.h
            target_w = window.width if window else self.w
            return torch.zeros(1, int(target_h), int(target_w))

    def _find_file_for_date(self, var_name, date_obj):
        patterns = [date_obj.strftime("%Y%m%d"), date_obj.strftime("%Y%j")]
        if var_name in self.file_cache:
            for fname, fpath in self.file_cache[var_name].items():
                for pat in patterns:
                    if pat in fname: return fpath
        return None

    def __len__(self):
        return len(self.dates)

    def __getitem__(self, idx):
        date_obj = self.dates[idx]
        date_key = date_obj.strftime("%Y%m%d")
        sample_tensors = {}

        # 1. Determine crop window
        crop_window = None
        crop_y, crop_x = 0, 0
        if self.is_train:
            max_y = self.h - self.patch_size
            max_x = self.w - self.patch_size
            if max_y > 0 and max_x > 0:
                crop_y = np.random.randint(0, max_y)
                crop_x = np.random.randint(0, max_x)
                crop_window = Window(crop_x, crop_y, self.patch_size, self.patch_size)

        target_h = self.patch_size if (self.is_train and crop_window) else self.h
        target_w = self.patch_size if (self.is_train and crop_window) else self.w

        # 2. Load static data & BoundaryMask
        for k, v in self.static_data.items():
            if self.is_train and crop_window:
                sample_tensors[k] = v[:, crop_y:crop_y + self.patch_size, crop_x:crop_x + self.patch_size]
            else:
                sample_tensors[k] = v

        if self.is_train and crop_window:
            boundary_patch = self.boundary_mask[:, crop_y:crop_y + self.patch_size, crop_x:crop_x + self.patch_size]
        else:
            boundary_patch = self.boundary_mask
        sample_tensors['BoundaryMask'] = boundary_patch

        # 3. Load dynamic data (T2m removed)
        dyn_vars = ['Albedo', 'LST', 'NDVI', 'SM', 'Wind', 'Label']
        for var in dyn_vars:
            file_path = self._find_file_for_date(var, date_obj)
            if file_path:
                sample_tensors[var] = self._read_and_normalize(file_path, var, window=crop_window)
            else:
                sample_tensors[var] = torch.zeros((1, target_h, target_w))

        # 4. Build station mask
        station_val = torch.zeros((1, target_h, target_w), dtype=torch.float32)
        station_mask = torch.zeros((1, target_h, target_w), dtype=torch.float32)

        if date_key in self.station_data_cache:
            points = self.station_data_cache[date_key]
            lbl_min, lbl_max = self.ranges.get('Label', (-50, 50))

            for (gr, gc, temp) in points:
                lr = gr - crop_y
                lc = gc - crop_x
                if 0 <= lr < target_h and 0 <= lc < target_w:
                    # Must be inside Boundary
                    if boundary_patch[0, lr, lc] > 0.5:
                        norm_temp = (temp - lbl_min) / (lbl_max - lbl_min + 1e-6)
                        station_val[0, lr, lc] = norm_temp
                        station_mask[0, lr, lc] = 1.0

        sample_tensors['StationVal'] = station_val
        sample_tensors['StationMask'] = station_mask

        return sample_tensors