import torch
import torch.nn.functional as F
from torch.utils.data import DataLoader
import numpy as np
import matplotlib.pyplot as plt
import os
import json
from tqdm import tqdm
import rasterio
from scipy.stats import gaussian_kde
from collections import OrderedDict
from matplotlib.font_manager import FontProperties
from matplotlib.ticker import FixedLocator
import warnings
import time

# Ignore warnings
warnings.filterwarnings("ignore")

# --- Import project modules ---
import data_loader
from data_loader import CausalDownscalingDataset, PHYSICAL_RANGES
from pci_sftnet import PCI_SFTNet

# ==========================================
# 1. Configure Paths and Parameters
# ==========================================
TEST_DATA_PATHS = {
    'Albedo': r'E:\Ta_fusion\paper_11\data\Albedo\daily_average',
    'LST': r'E:\Ta_fusion\paper_11\data\LST\daily\origin_area_463',
    'NDVI': r'E:\Ta_fusion\paper_11\data\NDVI\NDVI_STF_results_processed',
    'SM': r'E:\Ta_fusion\paper_11\data\SM\daily\origin_area_463',
    'Wind': r'E:\Ta_fusion\paper_11\data\windspeed\daily\origin_area_463',

    # [Target] High-resolution ground truth generated by RF (as Label)
    'Label': r'E:\graduation project\coding\RandomForest\output\results_LSTM_Calibrated_Daily',

    # [Static] Topographic data
    'Aspect': r'E:\Ta_fusion\paper_11\data\Landform\aspect\aspect_area_463.tif',
    'DEM': r'E:\Ta_fusion\paper_11\data\Landform\DEM\origin_area_463\DEM_area_463.tif',
    'Slope': r'E:\Ta_fusion\paper_11\data\Landform\slope\slope_area.tif',

    # [Station] Station data
    'Stations': r'E:\Ta_fusion\paper_11\data\yangtze_river_delta_station_data_2016\yangtze_stations_NOAA_daily',

    # [Boundary] Boundary SHP
    'Boundary': r'E:\graduation project\coding\详细边界\boundary.shp'
}

# Force update DataLoader paths
print("🔄 Updating data paths to test set paths...")
data_loader.DATA_PATHS.update(TEST_DATA_PATHS)

# Run configuration
PCMCI_JSON_PATH = r'E:\graduation project\coding\PCI-SFTNet\Causality_tree\PCMCI_Nonlinear_Analysis_Output\consensus_structure\consensus_pcmci_tree_NAMES.txt'
CHECKPOINT_PATH = './checkpoints/best_model.pth'
OUTPUT_DIR = './test_results_full_image'  # Modify output directory for distinction
TIF_OUTPUT_DIR = os.path.join(OUTPUT_DIR, 'tif_files')
STATION_SCATTER_PATH = os.path.join(OUTPUT_DIR, 'station_scatter_density.png')

TEST_START = '2016-01-01'
TEST_END = '2016-12-31'
GPU_ID = 0

# Sliding window fallback parameters (used when VRAM is insufficient for full image)
FALLBACK_PATCH_SIZE = 512
FALLBACK_OVERLAP = 64

# --- Plotting style settings ---
plt.rcParams['font.family'] = 'Times New Roman'
plt.rcParams['font.sans-serif'] = ['Times New Roman', 'SimSun']
plt.rcParams['axes.unicode_minus'] = False
try:
    SimSun_font = FontProperties(fname=r"C:\Windows\Fonts\simsun.ttc", size=40)
except:
    SimSun_font = FontProperties(family='SimSun', size=40)


# ==========================================
# 2. Utility Functions
# ==========================================

def calculate_metrics(y_true, y_pred):
    """Calculate RMSE, MAE, R2, PCC"""
    rmse = np.sqrt(np.mean((y_true - y_pred) ** 2))
    mae = np.mean(np.abs(y_true - y_pred))

    ss_res = np.sum((y_true - y_pred) ** 2)
    ss_tot = np.sum((y_true - np.mean(y_true)) ** 2)
    r2 = 1 - (ss_res / (ss_tot + 1e-8))

    vx = y_true - np.mean(y_true)
    vy = y_pred - np.mean(y_pred)
    pcc = np.sum(vx * vy) / (np.sqrt(np.sum(vx ** 2)) * np.sqrt(np.sum(vy ** 2)) + 1e-8)

    return rmse, mae, r2, pcc


def inverse_normalize(tensor, var_name='Label'):
    # If Label statistics don't exist, try T2m, or return directly
    if var_name not in PHYSICAL_RANGES:
        if var_name == 'Label' and 'T2m' in PHYSICAL_RANGES:
            var_name = 'T2m'
        else:
            return tensor
    min_val, max_val = PHYSICAL_RANGES[var_name]
    return tensor * (max_val - min_val) + min_val


def save_geotiff(path, data, profile, nodata_value=-9999.0):
    profile.update({
        'driver': 'GTiff', 'dtype': 'float32', 'count': 1,
        'compress': 'lzw', 'nodata': nodata_value
    })
    data_filled = np.nan_to_num(data, nan=nodata_value)
    with rasterio.open(path, 'w', **profile) as dst:
        dst.write(data_filled.astype(np.float32), 1)


def plot_station_scatter(obs, pred, save_path):
    """Plot station validation scatter"""
    valid_mask = ~np.isnan(obs) & ~np.isnan(pred)
    y_true, y_pred = obs[valid_mask], pred[valid_mask]

    if len(y_true) == 0: return

    rmse, mae, r2, pcc = calculate_metrics(y_true, y_pred)

    # Downsample for plotting
    plot_idx = np.random.choice(len(y_true), min(10000, len(y_true)), replace=False)
    x, y = y_true[plot_idx], y_pred[plot_idx]

    # Calculate density
    xy = np.vstack([x, y])
    try:
        z = gaussian_kde(xy)(xy)
        idx = z.argsort()
        x, y, z = x[idx], y[idx], z[idx]
    except:
        z = np.ones_like(x)

    plt.figure(figsize=(10, 9))
    plt.scatter(x, y, c=z, s=20, cmap='Spectral_r', alpha=0.8)

    # Reference line
    limits = [-10, 45]
    plt.plot(limits, limits, 'r-', lw=2, label='1:1 Line')

    # Fit line
    coef = np.polyfit(y_true, y_pred, 1)
    poly1d_fn = np.poly1d(coef)
    plt.plot(limits, poly1d_fn(limits), 'k--', lw=2, label='Fit Line')

    plt.xlim(limits);
    plt.ylim(limits)
    plt.xlabel("Observed T2m (°C)", fontsize=20)
    plt.ylabel("Predicted T2m (°C)", fontsize=20)

    stats_text = f'RMSE={rmse:.2f}\nMAE={mae:.2f}\nR²={r2:.2f}\nPCC={pcc:.2f}'
    plt.gca().text(0.05, 0.95, stats_text, transform=plt.gca().transAxes,
                   fontsize=18, verticalalignment='top',
                   bbox=dict(boxstyle='round', facecolor='white', alpha=0.8))

    plt.grid(True, linestyle='--', alpha=0.5)
    plt.tight_layout()
    plt.savefig(save_path, dpi=300)
    plt.close()


def save_visualization(date_str, pred, target, save_dir):
    """Plot simple spatial comparison"""
    pred_img = pred.squeeze().cpu().numpy()
    tar_img = target.squeeze().cpu().numpy()

    plt.figure(figsize=(12, 4))

    vmin, vmax = np.nanmin(tar_img), np.nanmax(tar_img)

    plt.subplot(1, 3, 1)
    plt.imshow(pred_img, cmap='jet', vmin=vmin, vmax=vmax)
    plt.title("Prediction")
    plt.axis('off')

    plt.subplot(1, 3, 2)
    plt.imshow(tar_img, cmap='jet', vmin=vmin, vmax=vmax)
    plt.title("Target (RF)")
    plt.axis('off')

    plt.subplot(1, 3, 3)
    diff = np.abs(pred_img - tar_img)
    plt.imshow(diff, cmap='coolwarm', vmin=0, vmax=3)
    plt.title("Abs Error")
    plt.axis('off')
    plt.colorbar()

    plt.tight_layout()
    plt.savefig(os.path.join(save_dir, f"{date_str}_compare.png"), dpi=150)
    plt.close()


# ==========================================
# 3. Core Inference Functions
# ==========================================

def full_image_inference(model, batch_data, device):
    """
    Attempt to infer directly on full image
    """
    model.eval()
    inputs = {}
    # Exclude non-input features
    exclude_keys = ['StationMask', 'StationVal', 'BoundaryMask', 'Label', 'T2m']

    for k, v in batch_data.items():
        if k not in exclude_keys:
            inputs[k] = v.to(device)

    # Direct forward propagation
    return model(inputs)


def sliding_window_inference(model, batch_data, device, patch_size=512, overlap=64):
    """
    Sliding window inference (Fallback)
    """
    ref = next(iter(batch_data.values()))
    _, _, H, W = ref.shape

    output_full = torch.zeros((1, 1, H, W), device=device)
    weight_map_full = torch.zeros((1, 1, H, W), device=device)

    # Create Hanning window for smooth tiling
    d_window = torch.hann_window(patch_size, periodic=False, device=device)
    window_2d = (d_window.unsqueeze(0) * d_window.unsqueeze(1)).view(1, 1, patch_size, patch_size)

    stride = patch_size - overlap
    y_starts = list(range(0, H - patch_size + 1, stride))
    if y_starts[-1] + patch_size < H: y_starts.append(H - patch_size)
    x_starts = list(range(0, W - patch_size + 1, stride))
    if x_starts[-1] + patch_size < W: x_starts.append(W - patch_size)

    exclude_keys = ['StationMask', 'StationVal', 'BoundaryMask', 'Label', 'T2m']

    model.eval()
    with torch.no_grad():
        for y in y_starts:
            for x in x_starts:
                patch_batch = {}
                for k, v in batch_data.items():
                    if k not in exclude_keys:
                        patch_batch[k] = v[:, :, y:y + patch_size, x:x + patch_size].to(device)

                pred_patch = model(patch_batch)
                output_full[:, :, y:y + patch_size, x:x + patch_size] += pred_patch * window_2d
                weight_map_full[:, :, y:y + patch_size, x:x + patch_size] += window_2d

    output_full /= (weight_map_full + 1e-6)
    return output_full


# ==========================================
# 4. Main Function
# ==========================================

def main_test():
    if not os.path.exists(OUTPUT_DIR): os.makedirs(OUTPUT_DIR)
    if not os.path.exists(TIF_OUTPUT_DIR): os.makedirs(TIF_OUTPUT_DIR)

    device = torch.device(f'cuda:{GPU_ID}' if torch.cuda.is_available() else 'cpu')
    print(f"🚀 Testing on device: {device}")

    # --- Read DEM to generate Valid Mask ---
    print(f"Loading Valid Mask from DEM...")
    dem_path = data_loader.DATA_PATHS['DEM']
    with rasterio.open(dem_path) as src:
        ref_profile = src.profile.copy()
        dem_data = src.read(1)
        valid_mask_numpy = (dem_data != src.nodata) & (dem_data > -1e30)

    # --- Load dataset ---
    # When is_train=False, Dataset returns full image data
    test_dataset = CausalDownscalingDataset(
        start_date=TEST_START, end_date=TEST_END, patch_size=FALLBACK_PATCH_SIZE, is_train=False
    )
    test_loader = DataLoader(test_dataset, batch_size=1, shuffle=False, num_workers=0)

    # --- Load model ---
    print("Loading Model...")
    model = PCI_SFTNet(pcmci_json_path=PCMCI_JSON_PATH).to(device)

    if os.path.exists(CHECKPOINT_PATH):
        checkpoint = torch.load(CHECKPOINT_PATH, map_location=device)
        state_dict = checkpoint if 'module.' not in list(checkpoint.keys())[0] else \
            OrderedDict({k.replace('module.', ''): v for k, v in checkpoint.items()})
        model.load_state_dict(state_dict)
        print(f"✅ Loaded weights: {CHECKPOINT_PATH}")
    else:
        print(f"❌ Checkpoint not found: {CHECKPOINT_PATH}")
        return

    # --- Statistics containers ---
    grid_metrics = {'rmse': [], 'mae': [], 'r2': []}
    station_data = {'obs': [], 'pred': []}

    print(f"Starting Inference ({len(test_dataset)} days)...")

    with torch.no_grad():
        for i, batch in enumerate(tqdm(test_loader)):
            current_date = test_dataset.dates[i].strftime("%Y%m%d")
            if 'Label' not in batch: continue

            # --- 🔥 Mixed Inference Logic 🔥 ---
            try:
                # 1. Prioritize full-image inference
                # print(f"Trying Full-Image Inference for {current_date}...")
                pred_norm = full_image_inference(model, batch, device)

            except RuntimeError as e:
                if 'out of memory' in str(e):
                    # 2. If OOM occurs, clear cache and switch to sliding window
                    # print(f"⚠️ OOM detected! Switching to Sliding Window (Patch={FALLBACK_PATCH_SIZE})...")
                    torch.cuda.empty_cache()
                    pred_norm = sliding_window_inference(
                        model, batch, device,
                        patch_size=FALLBACK_PATCH_SIZE,
                        overlap=FALLBACK_OVERLAP
                    )
                else:
                    raise e

            # --- Post-processing ---
            pred_norm = torch.clamp(pred_norm, 0.0, 1.0)
            boundary_mask = batch['BoundaryMask'].to(device)
            valid_tensor = torch.from_numpy(valid_mask_numpy).to(device)

            # Inverse normalization
            pred_real = inverse_normalize(pred_norm, 'Label')
            target_real = inverse_normalize(batch['Label'].to(device), 'Label')

            # Apply mask (Boundary & DEM Valid)
            final_mask = (boundary_mask > 0.5) & valid_tensor

            pred_real[~final_mask] = float('nan')
            target_real[~final_mask] = float('nan')

            # Physical range filtering (-50 ~ 60)
            pred_real[(pred_real < -50) | (pred_real > 60)] = float('nan')

            # --- Calculate Grid Metrics (vs RF) ---
            p_flat = pred_real.cpu().numpy().flatten()
            t_flat = target_real.cpu().numpy().flatten()
            mask = ~np.isnan(p_flat) & ~np.isnan(t_flat)

            if mask.sum() > 0:
                rmse, mae, r2, _ = calculate_metrics(t_flat[mask], p_flat[mask])
                grid_metrics['rmse'].append(rmse)
                grid_metrics['mae'].append(mae)
                grid_metrics['r2'].append(r2)

            # --- Save TIF ---
            tif_name = f"Pred_T2m_{current_date}.tif"
            save_geotiff(os.path.join(TIF_OUTPUT_DIR, tif_name),
                         pred_real.squeeze().cpu().numpy(), ref_profile)

            # --- Simple visualization (every 10 days) ---
            if i % 10 == 0:
                save_visualization(current_date, pred_real, target_real, OUTPUT_DIR)

            # --- Collect station validation data ---
            if 'StationVal' in batch:
                st_val_norm = batch['StationVal'].to(device)
                st_mask = batch['StationMask'].to(device)

                # Stations must be within valid area
                valid_st = (st_mask > 0.5) & final_mask

                if valid_st.sum() > 0:
                    st_obs = inverse_normalize(st_val_norm, 'Label')[valid_st]
                    st_pred = pred_real[valid_st]

                    station_data['obs'].append(st_obs.cpu().numpy())
                    station_data['pred'].append(st_pred.cpu().numpy())

    # ==========================================
    # 5. Results Summary
    # ==========================================
    print("\n" + "=" * 40)
    print("           TEST RESULTS           ")
    print("=" * 40)

    if grid_metrics['rmse']:
        print(f"🌍 [Grid vs RF Label] Average:")
        print(f"   RMSE: {np.mean(grid_metrics['rmse']):.4f}")
        print(f"   MAE : {np.mean(grid_metrics['mae']):.4f}")
        print(f"   R²  : {np.mean(grid_metrics['r2']):.4f}")

    if station_data['obs']:
        all_obs = np.concatenate(station_data['obs'])
        all_pred = np.concatenate(station_data['pred'])

        valid = ~np.isnan(all_obs) & ~np.isnan(all_pred)
        all_obs, all_pred = all_obs[valid], all_pred[valid]

        rmse, mae, r2, pcc = calculate_metrics(all_obs, all_pred)
        print("-" * 40)
        print(f"🔭 [Station Validation] ({len(all_obs)} points):")
        print(f"   RMSE: {rmse:.4f}")
        print(f"   MAE : {mae:.4f}")
        print(f"   R²  : {r2:.4f}")
        print(f"   PCC : {pcc:.4f}")

        plot_station_scatter(all_obs, all_pred, STATION_SCATTER_PATH)
        print(f"📊 Scatter plot saved to: {STATION_SCATTER_PATH}")

    print("=" * 40)
    print(f"✅ Testing Complete. TIFs saved in: {TIF_OUTPUT_DIR}")


if __name__ == '__main__':
    main_test()